language: bash
services: docker
before_install:
  - cd 17.RestwithSpringBootUdemy.eclipse.docker
  - echo "We are in the docker folder"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}"| docker login --username "${DOCKER_USER}" --password-stdin
deploy:
  provider:script
  script: 
     docker push paulohfcosta/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false